//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterUnitCase.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Request_Client = new HashSet<Request_Client>();
        }
    
        public int ID { get; set; }
        public int CreatorCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int EmployerCode { get; set; }
        public string StatusNote { get; set; }
        public int StatusCode { get; set; }
        public bool IsGroup { get; set; }
        public string Goal { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string GroupTitle { get; set; }
    
        public virtual Employer Employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Client> Request_Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
