//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterUnitCase.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Client
    {
        public int ID { get; set; }
        public int RequestCode { get; set; }
        public int ClientCode { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Request Request { get; set; }
    }
}
