//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Request_Client = new HashSet<Request_Client>();
        }
    
        public int ID { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public string Note { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string PassportSerial { get; set; }
        public string PassportNumber { get; set; }
        public byte[] PassportScan { get; set; }
        public byte[] Photo { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SurName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Client> Request_Client { get; set; }
    }
}
