//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Client
    {
        public int ID { get; set; }
        public int RequestCode { get; set; }
        public int ClientCode { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Request Request { get; set; }
    }
}
